services:
  - type: web_service
    name: ttrss
    env: docker
    plan: free
    region: oregon
    # Используем готовый образ, без Dockerfile
    dockerRepository: wangqiru/ttrss
    dockerTag: latest

    # Автообновление при пуше не требуется (образ обновляется в Docker Hub)
    autoDeploy: false

    # Переменные окружения для TT-RSS
    envVars:
      - key: SELF_URL_PATH
        value: https://ttrss.onrender.com/
      - key: DB_TYPE
        value: pgsql
      - key: TZ
        value: Europe/Moscow

    # Бесплатная база Postgres, параметры которой Render подставит в DB_*
    databases:
      - name: ttrss-db
        plan: free
