services:
  - type: web
    name: ttrss
    runtime: image
    image:
      url: wangqiru/ttrss:latest
    plan: free
    region: oregon
    envVars:
      - key: SELF_URL_PATH
        value: https://ttrss.onrender.com/
      - key: DB_TYPE
        value: pgsql
      - key: TZ
        value: Europe/Moscow

databases:
  - name: ttrss-db
    plan: free
